version: "3"
services:
  app:
    image: app
    build: .
    command: gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:80 --timeout 3600 --log-config /app/gunicorn.conf
    ports:
      - 8051:80
    networks:
    - elknetwork
  

networks:
  elknetwork:
    external: true